global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['web:5000']  # "web" is the Flask service name from docker-compose.yaml
rule_files:
  - "alert.rules.yml"
